// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/item.proto

package me.timyang.personal.company;

public final class ItemProto {
  private ItemProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:company.Item)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string date = 1;</code>
     */
    boolean hasDate();
    /**
     * <code>optional string date = 1;</code>
     */
    java.lang.String getDate();
    /**
     * <code>optional string date = 1;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>optional string tax_code = 2;</code>
     */
    boolean hasTaxCode();
    /**
     * <code>optional string tax_code = 2;</code>
     */
    java.lang.String getTaxCode();
    /**
     * <code>optional string tax_code = 2;</code>
     */
    com.google.protobuf.ByteString
        getTaxCodeBytes();

    /**
     * <code>optional string tax_name = 3;</code>
     */
    boolean hasTaxName();
    /**
     * <code>optional string tax_name = 3;</code>
     */
    java.lang.String getTaxName();
    /**
     * <code>optional string tax_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getTaxNameBytes();

    /**
     * <code>optional double money = 4;</code>
     */
    boolean hasMoney();
    /**
     * <code>optional double money = 4;</code>
     */
    double getMoney();

    /**
     * <code>optional int32 count = 5;</code>
     */
    boolean hasCount();
    /**
     * <code>optional int32 count = 5;</code>
     */
    int getCount();

    /**
     * <code>optional double price = 6;</code>
     */
    boolean hasPrice();
    /**
     * <code>optional double price = 6;</code>
     */
    double getPrice();

    /**
     * <code>optional string unit = 7;</code>
     */
    boolean hasUnit();
    /**
     * <code>optional string unit = 7;</code>
     */
    java.lang.String getUnit();
    /**
     * <code>optional string unit = 7;</code>
     */
    com.google.protobuf.ByteString
        getUnitBytes();

    /**
     * <code>optional string company_number = 8;</code>
     */
    boolean hasCompanyNumber();
    /**
     * <code>optional string company_number = 8;</code>
     */
    java.lang.String getCompanyNumber();
    /**
     * <code>optional string company_number = 8;</code>
     */
    com.google.protobuf.ByteString
        getCompanyNumberBytes();

    /**
     * <code>optional string company_name = 9;</code>
     */
    boolean hasCompanyName();
    /**
     * <code>optional string company_name = 9;</code>
     */
    java.lang.String getCompanyName();
    /**
     * <code>optional string company_name = 9;</code>
     */
    com.google.protobuf.ByteString
        getCompanyNameBytes();

    /**
     * <code>optional string company_address = 10;</code>
     */
    boolean hasCompanyAddress();
    /**
     * <code>optional string company_address = 10;</code>
     */
    java.lang.String getCompanyAddress();
    /**
     * <code>optional string company_address = 10;</code>
     */
    com.google.protobuf.ByteString
        getCompanyAddressBytes();

    /**
     * <code>optional string phone = 11;</code>
     */
    boolean hasPhone();
    /**
     * <code>optional string phone = 11;</code>
     */
    java.lang.String getPhone();
    /**
     * <code>optional string phone = 11;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>optional string fax = 12;</code>
     */
    boolean hasFax();
    /**
     * <code>optional string fax = 12;</code>
     */
    java.lang.String getFax();
    /**
     * <code>optional string fax = 12;</code>
     */
    com.google.protobuf.ByteString
        getFaxBytes();

    /**
     * <code>optional string zip = 13;</code>
     */
    boolean hasZip();
    /**
     * <code>optional string zip = 13;</code>
     */
    java.lang.String getZip();
    /**
     * <code>optional string zip = 13;</code>
     */
    com.google.protobuf.ByteString
        getZipBytes();
  }
  /**
   * Protobuf type {@code company.Item}
   */
  public  static final class Item extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:company.Item)
      ItemOrBuilder {
    // Use Item.newBuilder() to construct.
    private Item(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Item() {
      date_ = "";
      taxCode_ = "";
      taxName_ = "";
      money_ = 0D;
      count_ = 0;
      price_ = 0D;
      unit_ = "";
      companyNumber_ = "";
      companyName_ = "";
      companyAddress_ = "";
      phone_ = "";
      fax_ = "";
      zip_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Item(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              date_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              taxCode_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              taxName_ = bs;
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              money_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              count_ = input.readInt32();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              price_ = input.readDouble();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              unit_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              companyNumber_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              companyName_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              companyAddress_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              phone_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              fax_ = bs;
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              zip_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.timyang.personal.company.ItemProto.internal_static_company_Item_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.timyang.personal.company.ItemProto.internal_static_company_Item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.timyang.personal.company.ItemProto.Item.class, me.timyang.personal.company.ItemProto.Item.Builder.class);
    }

    private int bitField0_;
    public static final int DATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object date_;
    /**
     * <code>optional string date = 1;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string date = 1;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string date = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAX_CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object taxCode_;
    /**
     * <code>optional string tax_code = 2;</code>
     */
    public boolean hasTaxCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string tax_code = 2;</code>
     */
    public java.lang.String getTaxCode() {
      java.lang.Object ref = taxCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taxCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tax_code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTaxCodeBytes() {
      java.lang.Object ref = taxCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taxCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAX_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object taxName_;
    /**
     * <code>optional string tax_name = 3;</code>
     */
    public boolean hasTaxName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string tax_name = 3;</code>
     */
    public java.lang.String getTaxName() {
      java.lang.Object ref = taxName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taxName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tax_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTaxNameBytes() {
      java.lang.Object ref = taxName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taxName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MONEY_FIELD_NUMBER = 4;
    private double money_;
    /**
     * <code>optional double money = 4;</code>
     */
    public boolean hasMoney() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double money = 4;</code>
     */
    public double getMoney() {
      return money_;
    }

    public static final int COUNT_FIELD_NUMBER = 5;
    private int count_;
    /**
     * <code>optional int32 count = 5;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 count = 5;</code>
     */
    public int getCount() {
      return count_;
    }

    public static final int PRICE_FIELD_NUMBER = 6;
    private double price_;
    /**
     * <code>optional double price = 6;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double price = 6;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int UNIT_FIELD_NUMBER = 7;
    private volatile java.lang.Object unit_;
    /**
     * <code>optional string unit = 7;</code>
     */
    public boolean hasUnit() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string unit = 7;</code>
     */
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          unit_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string unit = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANY_NUMBER_FIELD_NUMBER = 8;
    private volatile java.lang.Object companyNumber_;
    /**
     * <code>optional string company_number = 8;</code>
     */
    public boolean hasCompanyNumber() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string company_number = 8;</code>
     */
    public java.lang.String getCompanyNumber() {
      java.lang.Object ref = companyNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          companyNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string company_number = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyNumberBytes() {
      java.lang.Object ref = companyNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANY_NAME_FIELD_NUMBER = 9;
    private volatile java.lang.Object companyName_;
    /**
     * <code>optional string company_name = 9;</code>
     */
    public boolean hasCompanyName() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string company_name = 9;</code>
     */
    public java.lang.String getCompanyName() {
      java.lang.Object ref = companyName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          companyName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string company_name = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyNameBytes() {
      java.lang.Object ref = companyName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANY_ADDRESS_FIELD_NUMBER = 10;
    private volatile java.lang.Object companyAddress_;
    /**
     * <code>optional string company_address = 10;</code>
     */
    public boolean hasCompanyAddress() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string company_address = 10;</code>
     */
    public java.lang.String getCompanyAddress() {
      java.lang.Object ref = companyAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          companyAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string company_address = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyAddressBytes() {
      java.lang.Object ref = companyAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 11;
    private volatile java.lang.Object phone_;
    /**
     * <code>optional string phone = 11;</code>
     */
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string phone = 11;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phone_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string phone = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FAX_FIELD_NUMBER = 12;
    private volatile java.lang.Object fax_;
    /**
     * <code>optional string fax = 12;</code>
     */
    public boolean hasFax() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string fax = 12;</code>
     */
    public java.lang.String getFax() {
      java.lang.Object ref = fax_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fax_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fax = 12;</code>
     */
    public com.google.protobuf.ByteString
        getFaxBytes() {
      java.lang.Object ref = fax_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fax_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZIP_FIELD_NUMBER = 13;
    private volatile java.lang.Object zip_;
    /**
     * <code>optional string zip = 13;</code>
     */
    public boolean hasZip() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string zip = 13;</code>
     */
    public java.lang.String getZip() {
      java.lang.Object ref = zip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          zip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string zip = 13;</code>
     */
    public com.google.protobuf.ByteString
        getZipBytes() {
      java.lang.Object ref = zip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, date_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taxCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, taxName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, money_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, count_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, price_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, unit_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, companyNumber_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, companyName_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, companyAddress_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, phone_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, fax_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, zip_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, date_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taxCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, taxName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, money_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, count_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, price_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, unit_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, companyNumber_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, companyName_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, companyAddress_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, phone_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, fax_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, zip_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.timyang.personal.company.ItemProto.Item)) {
        return super.equals(obj);
      }
      me.timyang.personal.company.ItemProto.Item other = (me.timyang.personal.company.ItemProto.Item) obj;

      boolean result = true;
      result = result && (hasDate() == other.hasDate());
      if (hasDate()) {
        result = result && getDate()
            .equals(other.getDate());
      }
      result = result && (hasTaxCode() == other.hasTaxCode());
      if (hasTaxCode()) {
        result = result && getTaxCode()
            .equals(other.getTaxCode());
      }
      result = result && (hasTaxName() == other.hasTaxName());
      if (hasTaxName()) {
        result = result && getTaxName()
            .equals(other.getTaxName());
      }
      result = result && (hasMoney() == other.hasMoney());
      if (hasMoney()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getMoney())
            == java.lang.Double.doubleToLongBits(
                other.getMoney()));
      }
      result = result && (hasCount() == other.hasCount());
      if (hasCount()) {
        result = result && (getCount()
            == other.getCount());
      }
      result = result && (hasPrice() == other.hasPrice());
      if (hasPrice()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getPrice())
            == java.lang.Double.doubleToLongBits(
                other.getPrice()));
      }
      result = result && (hasUnit() == other.hasUnit());
      if (hasUnit()) {
        result = result && getUnit()
            .equals(other.getUnit());
      }
      result = result && (hasCompanyNumber() == other.hasCompanyNumber());
      if (hasCompanyNumber()) {
        result = result && getCompanyNumber()
            .equals(other.getCompanyNumber());
      }
      result = result && (hasCompanyName() == other.hasCompanyName());
      if (hasCompanyName()) {
        result = result && getCompanyName()
            .equals(other.getCompanyName());
      }
      result = result && (hasCompanyAddress() == other.hasCompanyAddress());
      if (hasCompanyAddress()) {
        result = result && getCompanyAddress()
            .equals(other.getCompanyAddress());
      }
      result = result && (hasPhone() == other.hasPhone());
      if (hasPhone()) {
        result = result && getPhone()
            .equals(other.getPhone());
      }
      result = result && (hasFax() == other.hasFax());
      if (hasFax()) {
        result = result && getFax()
            .equals(other.getFax());
      }
      result = result && (hasZip() == other.hasZip());
      if (hasZip()) {
        result = result && getZip()
            .equals(other.getZip());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      if (hasTaxCode()) {
        hash = (37 * hash) + TAX_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getTaxCode().hashCode();
      }
      if (hasTaxName()) {
        hash = (37 * hash) + TAX_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getTaxName().hashCode();
      }
      if (hasMoney()) {
        hash = (37 * hash) + MONEY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getMoney()));
      }
      if (hasCount()) {
        hash = (37 * hash) + COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getCount();
      }
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getPrice()));
      }
      if (hasUnit()) {
        hash = (37 * hash) + UNIT_FIELD_NUMBER;
        hash = (53 * hash) + getUnit().hashCode();
      }
      if (hasCompanyNumber()) {
        hash = (37 * hash) + COMPANY_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getCompanyNumber().hashCode();
      }
      if (hasCompanyName()) {
        hash = (37 * hash) + COMPANY_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getCompanyName().hashCode();
      }
      if (hasCompanyAddress()) {
        hash = (37 * hash) + COMPANY_ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getCompanyAddress().hashCode();
      }
      if (hasPhone()) {
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + getPhone().hashCode();
      }
      if (hasFax()) {
        hash = (37 * hash) + FAX_FIELD_NUMBER;
        hash = (53 * hash) + getFax().hashCode();
      }
      if (hasZip()) {
        hash = (37 * hash) + ZIP_FIELD_NUMBER;
        hash = (53 * hash) + getZip().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.timyang.personal.company.ItemProto.Item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.timyang.personal.company.ItemProto.Item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.timyang.personal.company.ItemProto.Item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.timyang.personal.company.ItemProto.Item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.timyang.personal.company.ItemProto.Item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.timyang.personal.company.ItemProto.Item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.timyang.personal.company.ItemProto.Item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.timyang.personal.company.ItemProto.Item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.timyang.personal.company.ItemProto.Item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.timyang.personal.company.ItemProto.Item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.timyang.personal.company.ItemProto.Item prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code company.Item}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:company.Item)
        me.timyang.personal.company.ItemProto.ItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.timyang.personal.company.ItemProto.internal_static_company_Item_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.timyang.personal.company.ItemProto.internal_static_company_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.timyang.personal.company.ItemProto.Item.class, me.timyang.personal.company.ItemProto.Item.Builder.class);
      }

      // Construct using me.timyang.personal.company.ItemProto.Item.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        taxCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        taxName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        money_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        price_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        unit_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        companyNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        companyName_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        companyAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        phone_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        fax_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        zip_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.timyang.personal.company.ItemProto.internal_static_company_Item_descriptor;
      }

      public me.timyang.personal.company.ItemProto.Item getDefaultInstanceForType() {
        return me.timyang.personal.company.ItemProto.Item.getDefaultInstance();
      }

      public me.timyang.personal.company.ItemProto.Item build() {
        me.timyang.personal.company.ItemProto.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.timyang.personal.company.ItemProto.Item buildPartial() {
        me.timyang.personal.company.ItemProto.Item result = new me.timyang.personal.company.ItemProto.Item(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.taxCode_ = taxCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.taxName_ = taxName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.money_ = money_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.unit_ = unit_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.companyNumber_ = companyNumber_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.companyName_ = companyName_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.companyAddress_ = companyAddress_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.phone_ = phone_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.fax_ = fax_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.zip_ = zip_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.timyang.personal.company.ItemProto.Item) {
          return mergeFrom((me.timyang.personal.company.ItemProto.Item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.timyang.personal.company.ItemProto.Item other) {
        if (other == me.timyang.personal.company.ItemProto.Item.getDefaultInstance()) return this;
        if (other.hasDate()) {
          bitField0_ |= 0x00000001;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasTaxCode()) {
          bitField0_ |= 0x00000002;
          taxCode_ = other.taxCode_;
          onChanged();
        }
        if (other.hasTaxName()) {
          bitField0_ |= 0x00000004;
          taxName_ = other.taxName_;
          onChanged();
        }
        if (other.hasMoney()) {
          setMoney(other.getMoney());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasUnit()) {
          bitField0_ |= 0x00000040;
          unit_ = other.unit_;
          onChanged();
        }
        if (other.hasCompanyNumber()) {
          bitField0_ |= 0x00000080;
          companyNumber_ = other.companyNumber_;
          onChanged();
        }
        if (other.hasCompanyName()) {
          bitField0_ |= 0x00000100;
          companyName_ = other.companyName_;
          onChanged();
        }
        if (other.hasCompanyAddress()) {
          bitField0_ |= 0x00000200;
          companyAddress_ = other.companyAddress_;
          onChanged();
        }
        if (other.hasPhone()) {
          bitField0_ |= 0x00000400;
          phone_ = other.phone_;
          onChanged();
        }
        if (other.hasFax()) {
          bitField0_ |= 0x00000800;
          fax_ = other.fax_;
          onChanged();
        }
        if (other.hasZip()) {
          bitField0_ |= 0x00001000;
          zip_ = other.zip_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.timyang.personal.company.ItemProto.Item parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.timyang.personal.company.ItemProto.Item) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object date_ = "";
      /**
       * <code>optional string date = 1;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string date = 1;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string date = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string date = 1;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string date = 1;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string date = 1;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object taxCode_ = "";
      /**
       * <code>optional string tax_code = 2;</code>
       */
      public boolean hasTaxCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string tax_code = 2;</code>
       */
      public java.lang.String getTaxCode() {
        java.lang.Object ref = taxCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taxCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tax_code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTaxCodeBytes() {
        java.lang.Object ref = taxCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taxCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tax_code = 2;</code>
       */
      public Builder setTaxCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        taxCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tax_code = 2;</code>
       */
      public Builder clearTaxCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        taxCode_ = getDefaultInstance().getTaxCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tax_code = 2;</code>
       */
      public Builder setTaxCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        taxCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object taxName_ = "";
      /**
       * <code>optional string tax_name = 3;</code>
       */
      public boolean hasTaxName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string tax_name = 3;</code>
       */
      public java.lang.String getTaxName() {
        java.lang.Object ref = taxName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taxName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tax_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTaxNameBytes() {
        java.lang.Object ref = taxName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taxName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tax_name = 3;</code>
       */
      public Builder setTaxName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        taxName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tax_name = 3;</code>
       */
      public Builder clearTaxName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        taxName_ = getDefaultInstance().getTaxName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tax_name = 3;</code>
       */
      public Builder setTaxNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        taxName_ = value;
        onChanged();
        return this;
      }

      private double money_ ;
      /**
       * <code>optional double money = 4;</code>
       */
      public boolean hasMoney() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double money = 4;</code>
       */
      public double getMoney() {
        return money_;
      }
      /**
       * <code>optional double money = 4;</code>
       */
      public Builder setMoney(double value) {
        bitField0_ |= 0x00000008;
        money_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double money = 4;</code>
       */
      public Builder clearMoney() {
        bitField0_ = (bitField0_ & ~0x00000008);
        money_ = 0D;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>optional int32 count = 5;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 count = 5;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 5;</code>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000010;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 5;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        count_ = 0;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>optional double price = 6;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double price = 6;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>optional double price = 6;</code>
       */
      public Builder setPrice(double value) {
        bitField0_ |= 0x00000020;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double price = 6;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000020);
        price_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object unit_ = "";
      /**
       * <code>optional string unit = 7;</code>
       */
      public boolean hasUnit() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string unit = 7;</code>
       */
      public java.lang.String getUnit() {
        java.lang.Object ref = unit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            unit_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string unit = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string unit = 7;</code>
       */
      public Builder setUnit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string unit = 7;</code>
       */
      public Builder clearUnit() {
        bitField0_ = (bitField0_ & ~0x00000040);
        unit_ = getDefaultInstance().getUnit();
        onChanged();
        return this;
      }
      /**
       * <code>optional string unit = 7;</code>
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        unit_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object companyNumber_ = "";
      /**
       * <code>optional string company_number = 8;</code>
       */
      public boolean hasCompanyNumber() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string company_number = 8;</code>
       */
      public java.lang.String getCompanyNumber() {
        java.lang.Object ref = companyNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            companyNumber_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string company_number = 8;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyNumberBytes() {
        java.lang.Object ref = companyNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          companyNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string company_number = 8;</code>
       */
      public Builder setCompanyNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        companyNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string company_number = 8;</code>
       */
      public Builder clearCompanyNumber() {
        bitField0_ = (bitField0_ & ~0x00000080);
        companyNumber_ = getDefaultInstance().getCompanyNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string company_number = 8;</code>
       */
      public Builder setCompanyNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        companyNumber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object companyName_ = "";
      /**
       * <code>optional string company_name = 9;</code>
       */
      public boolean hasCompanyName() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string company_name = 9;</code>
       */
      public java.lang.String getCompanyName() {
        java.lang.Object ref = companyName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            companyName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string company_name = 9;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyNameBytes() {
        java.lang.Object ref = companyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          companyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string company_name = 9;</code>
       */
      public Builder setCompanyName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        companyName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string company_name = 9;</code>
       */
      public Builder clearCompanyName() {
        bitField0_ = (bitField0_ & ~0x00000100);
        companyName_ = getDefaultInstance().getCompanyName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string company_name = 9;</code>
       */
      public Builder setCompanyNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        companyName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object companyAddress_ = "";
      /**
       * <code>optional string company_address = 10;</code>
       */
      public boolean hasCompanyAddress() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string company_address = 10;</code>
       */
      public java.lang.String getCompanyAddress() {
        java.lang.Object ref = companyAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            companyAddress_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string company_address = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyAddressBytes() {
        java.lang.Object ref = companyAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          companyAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string company_address = 10;</code>
       */
      public Builder setCompanyAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        companyAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string company_address = 10;</code>
       */
      public Builder clearCompanyAddress() {
        bitField0_ = (bitField0_ & ~0x00000200);
        companyAddress_ = getDefaultInstance().getCompanyAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string company_address = 10;</code>
       */
      public Builder setCompanyAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        companyAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>optional string phone = 11;</code>
       */
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string phone = 11;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            phone_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string phone = 11;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phone = 11;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 11;</code>
       */
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000400);
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 11;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        phone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fax_ = "";
      /**
       * <code>optional string fax = 12;</code>
       */
      public boolean hasFax() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string fax = 12;</code>
       */
      public java.lang.String getFax() {
        java.lang.Object ref = fax_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fax_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fax = 12;</code>
       */
      public com.google.protobuf.ByteString
          getFaxBytes() {
        java.lang.Object ref = fax_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fax_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fax = 12;</code>
       */
      public Builder setFax(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        fax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fax = 12;</code>
       */
      public Builder clearFax() {
        bitField0_ = (bitField0_ & ~0x00000800);
        fax_ = getDefaultInstance().getFax();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fax = 12;</code>
       */
      public Builder setFaxBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        fax_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object zip_ = "";
      /**
       * <code>optional string zip = 13;</code>
       */
      public boolean hasZip() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string zip = 13;</code>
       */
      public java.lang.String getZip() {
        java.lang.Object ref = zip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            zip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string zip = 13;</code>
       */
      public com.google.protobuf.ByteString
          getZipBytes() {
        java.lang.Object ref = zip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string zip = 13;</code>
       */
      public Builder setZip(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        zip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string zip = 13;</code>
       */
      public Builder clearZip() {
        bitField0_ = (bitField0_ & ~0x00001000);
        zip_ = getDefaultInstance().getZip();
        onChanged();
        return this;
      }
      /**
       * <code>optional string zip = 13;</code>
       */
      public Builder setZipBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        zip_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:company.Item)
    }

    // @@protoc_insertion_point(class_scope:company.Item)
    private static final me.timyang.personal.company.ItemProto.Item DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.timyang.personal.company.ItemProto.Item();
    }

    public static me.timyang.personal.company.ItemProto.Item getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Item>
        PARSER = new com.google.protobuf.AbstractParser<Item>() {
      public Item parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Item(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Item> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Item> getParserForType() {
      return PARSER;
    }

    public me.timyang.personal.company.ItemProto.Item getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_Item_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024src/proto/item.proto\022\007company\"\343\001\n\004Item" +
      "\022\014\n\004date\030\001 \001(\t\022\020\n\010tax_code\030\002 \001(\t\022\020\n\010tax_" +
      "name\030\003 \001(\t\022\r\n\005money\030\004 \001(\001\022\r\n\005count\030\005 \001(\005" +
      "\022\r\n\005price\030\006 \001(\001\022\014\n\004unit\030\007 \001(\t\022\026\n\016company" +
      "_number\030\010 \001(\t\022\024\n\014company_name\030\t \001(\t\022\027\n\017c" +
      "ompany_address\030\n \001(\t\022\r\n\005phone\030\013 \001(\t\022\013\n\003f" +
      "ax\030\014 \001(\t\022\013\n\003zip\030\r \001(\tB(\n\033me.timyang.pers" +
      "onal.companyB\tItemProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_company_Item_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_company_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_Item_descriptor,
        new java.lang.String[] { "Date", "TaxCode", "TaxName", "Money", "Count", "Price", "Unit", "CompanyNumber", "CompanyName", "CompanyAddress", "Phone", "Fax", "Zip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
